apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ketchup-ui.fullname" . }}
  labels:
    {{- include "ketchup-ui.labels" . | nindent 4 }}
data:
  config.js: |-
    {{- required "Please provide a valid application configuration file by setting property applicationProperties." .Values.applicationProperties | nindent 4}}