apiVersion: v1
kind: Service
metadata:
  name: {{ include "ketchup-ui.fullname" . }}
  labels:
    {{- include "ketchup-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} #targetPort will same as port and nodePort will be automatically picked.
      protocol: TCP
      name: http
  selector:
    {{- include "ketchup-ui.selectorLabels" . | nindent 4 }}
